# Generated by Django 4.2.4 on 2023-08-22 23:10

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('url_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=45, verbose_name='Model')),
                ('url_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='model', unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('image', models.ImageField(max_length=500, upload_to='', verbose_name='Photo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.brand', verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=45, verbose_name='Maker')),
                ('identification_number', models.CharField(max_length=45, verbose_name='Identification Number')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('widht', models.IntegerField(verbose_name='Widht')),
                ('longitude', models.IntegerField(verbose_name='Longitude')),
                ('km', models.IntegerField(verbose_name='KM')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internal.car', verbose_name='Car')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.state', verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='brand',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.state', verbose_name='State'),
        ),
    ]
